### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
I can't believe you broke the build!

**Comment by johnelse** [comment]
:construction: :boom: :gun:

**Comment by simonjbeaumont** [comment]
borked due to https://github.com/simonjbeaumont/ocaml-travis-coveralls/pull/10

**Comment by simonjbeaumont** [comment]
I'm hoping this is unborked now and ive restarted the travis job

**Pull request merged**
